# Generated by Django 5.0.3 on 2024-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_question_question_type_question_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='trigger_answers',
            field=models.ManyToManyField(blank=True, related_name='trigger_questions', to='main.answer'),
        ),
    ]
