# Generated by Django 5.0.3 on 2024-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_trigger_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='trigger_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='trigger_answer_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
